### PR TITLE
Configure UI Packages To Meet Our Requirements

### PR DESCRIPTION
**Pull request by Sepehrworklife**
- Remove unnecessary files 97605a4cdff9e5e445db131e68f33f5a19431125 fd31060e298df7c2f3bcb9d94531782f4ca5bfe6
- Configure UI package a3c924fb484b133c3f4dafd7fe9116356d161fef
- Configure WEB app 240e1f52fbeb08cd4e19d85a043cf05d4684242d 9fc33a366ba697809ae71442415cbab6c382bb36
- Other things 426e5722636d0767e041ff8a744c7998b3cda005

### CODE REVIEW

**Comment by Sepehrworklife** [comment]
@erfanMirhoseini78 @amiradiib 
The way you should consider reviewing this PR:
1. Have basic knowledge about Monorepo
2. Get familiar with turborepo
3. Open `package.json` on both the `web` and `ui` packages to see what are the dependencies.
4. Read about the [Shadcn](https://ui.shadcn.com/)
The icon set we will use is [Lucid-React](https://lucide.dev/guide/packages/lucide-react)

If you have any question feel free to ask :smile: :blush:

**Comment by Sepehrworklife** [comment]
@erfanMirhoseini78 @amiradiib This PR will be on hold until you approve it, so please give it time.

**Comment by amiradiib** [comment]
> @erfanMirhoseini78 @amiradiib The way you should consider reviewing this PR:
> 
> 1. Have basic knowledge about Monorepo
> 2. Get familiar with turborepo
> 3. Open `package.json` on both the `web` and `ui` packages to see what are the dependencies.
> 4. Read about the [Shadcn](https://ui.shadcn.com/)
>    The icon set we will use is [Lucid-React](https://lucide.dev/guide/packages/lucide-react)
> 
> If you have any question feel free to ask 😄 😊

@Sepehrworklife understood generally about monorepos with this [article](https://www.atlassian.com/git/tutorials/monorepos)

**Review by amiradiib — APPROVED** [review]
Good job @Sepehrworklife 
Everything’s fine

**Comment by Sepehrworklife** [comment]
@amiradiib Thanks :heart:

**Review by erfanMirhoseini78 — COMMENTED** [review]
Good job @Sepehrworklife
Everything’s fine

**Review by erfanMirhoseini78 — APPROVED** [review]

**Pull request merged**
